### PR TITLE
Add snackbar and manage error messages

### PR DESCRIPTION
**Pull request by med-hedi**
Signed-off-by: Mohamed Hedi Khefacha <mohamed.hedi@rte-france.com>

### CODE REVIEW

**Comment by med-hedi** [comment]
@geofjamg I have just tested the branch and I confirm that the check on the name of the list works and that the button is disabled and the message is displayed in the snackbar 
gridactions

**Comment by geofjamg** [comment]
> @geofjamg I have just tested the branch and I confirm that the check on the name of the list works and that the button is disabled and the message is displayed in the snackbar
> gridactions

The snackbar is not the right place for this error. Just display it on the creation dialog.
Also you should move it in another PR.

**Comment by med-hedi** [comment]
> > @geofjamg I have just tested the branch and I confirm that the check on the name of the list works and that the button is disabled and the message is displayed in the snackbar
> > gridactions
> 
> The snackbar is not the right place for this error. Just display it on the creation dialog.
> Also you should move it in another PR.

Do you want to display the error under the input field without going through the snackbar?

**Comment by geofjamg** [comment]
> > > @geofjamg I have just tested the branch and I confirm that the check on the name of the list works and that the button is disabled and the message is displayed in the snackbar
> > > gridactions
> > 
> > 
> > The snackbar is not the right place for this error. Just display it on the creation dialog.
> > Also you should move it in another PR.
> 
> Do you want to display the error under the input field without going through the snackbar?

yes

**Comment by med-hedi** [comment]
@geofjamg it is done, this is the PR which manages the display of the error in the popup https://github.com/gridsuite/gridactions-app/pull/28

**Review by geofjamg — APPROVED** [review]

**Pull request merged**
